require('keymaps')
require('plugins.lazy')
require('plugins.misc')
require('plugins.lualine')
require('options')
require('misc')
require('plugins.dap')
require('plugins.tele')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.trouble')
require('plugins.zenmode')
require('plugins.codesnap')
require('plugins.harpoon')
require('plugins.lazygit')
require('plugins.neotree')
require('plugins.hop')
require('plugins.sess')
require('plugins.gitsigns')
require('plugins.scrollview')
require('plugins.fold')
-- require('plugins.cmp')
require('plugins.goto')
require('plugins.statuscolumn')
require('plugins.null-ls')
require('plugins.cppgenerate')
-- require('plugins.htmlcss')
